#!/bin/sh
[ -d "landscape" ] && echo "Directory landscape exists."
[ ! -d "landscape" ] && mkdir landscape
[ -d "portrait" ] && echo "Directory portrait exists."
[ ! -d "portrait" ] && mkdir portrait
identify -format "%f %w %h\n" *.* | awk  '{if(0+$2 > 0 && 0+$3 > 0) {if($2/$3 >= 1) {system("mv "$1" landscape")} else {system("mv "$1" portrait")}}}'
